<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:airo="https://www.360airo.com/sitemap"
  exclude-result-prefixes="s airo">
  <xsl:output method="html" encoding="UTF-8"/>
  <xsl:template match="/">
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>Sitemap</title>
        <style>
          * { box-sizing: border-box; }
          body { margin: 0; color: #080d1a; font-family: Arial, sans-serif; font-size: 18px; }
          header { padding: 32px 42px 48px; color: white; background: #111c3d; }
          h1 { margin: 0 0 24px; font-size: 36px; }
          header p { margin: 0 0 18px; line-height: 1.55; }
          header a { color: white; }
          main { padding: 30px 44px; }
          .crumb { margin-bottom: 42px; font-size: 22px; }
          table { width: 100%; border-collapse: collapse; }
          th, td { padding: 22px 8px; text-align: left; border-bottom: 1px solid #ccc; }
          th { font-size: 20px; }
          tbody tr:nth-child(even) { background: #f2f2f2; }
          a { color: #0000ee; }
          @media (max-width: 700px) { header, main { padding-left: 20px; padding-right: 20px; } body { font-size: 14px; } }
        </style>
      </head>
      <body>
        <header>
          <h1>Sitemap</h1>
          <p>Generated by 360Airo, this is an XML Sitemap meant to be consumed by search engines like Google or Bing.</p>
          <p>You can find more information about XML Sitemaps at <a href="https://www.sitemaps.org/">sitemaps.org</a>.</p>
          <p>This sitemap index contains <xsl:value-of select="count(s:sitemapindex/s:sitemap)"/> sitemaps.</p>
        </header>
        <main>
          <div class="crumb">Home › <strong>Sitemap Index</strong></div>
          <table>
            <thead><tr><th>URL</th><th>URL Count</th><th>Last Updated</th></tr></thead>
            <tbody>
              <xsl:for-each select="s:sitemapindex/s:sitemap">
                <tr>
                  <td><a href="{s:loc}"><xsl:value-of select="s:loc"/></a></td>
                  <td><xsl:value-of select="@airo:url-count"/></td>
                  <td><xsl:value-of select="translate(substring(s:lastmod, 1, 19), 'T', ' ')"/> UTC</td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
        </main>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
