<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
  exclude-result-prefixes="s image">
  <xsl:output method="html" encoding="UTF-8"/>
  <xsl:template match="/">
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>URL Sitemap</title>
        <style>
          * { box-sizing: border-box; }
          body { margin: 0; color: #080d1a; font-family: Arial, sans-serif; font-size: 18px; }
          header { padding: 40px 42px 48px; color: white; background: #111c3d; }
          h1 { margin: 0 0 24px; font-size: 36px; }
          header p { margin: 0 0 18px; line-height: 1.55; }
          header a { color: white; }
          main { padding: 30px 44px; }
          .crumb { margin-bottom: 42px; font-size: 22px; }
          table { width: 100%; border-collapse: collapse; table-layout: fixed; }
          th, td { padding: 18px 8px; text-align: left; border-bottom: 1px solid #ccc; overflow-wrap: anywhere; }
          th { font-size: 20px; }
          tbody tr:nth-child(even) { background: #f2f2f2; }
          a { color: #0000ee; }
          .url { width: 34%; } .small { width: 13%; } .updated { width: 27%; }
          @media (max-width: 700px) { header, main { padding-left: 20px; padding-right: 20px; } body { font-size: 14px; } }
        </style>
      </head>
      <body>
        <header>
          <h1>URL Sitemap</h1>
          <p>Generated by 360Airo, this is an XML Sitemap meant to be consumed by search engines like Google or Bing.</p>
          <p>You can find more information about XML Sitemaps at <a href="https://www.sitemaps.org/">sitemaps.org</a>.</p>
          <p>This sitemap contains <xsl:value-of select="count(s:urlset/s:url)"/> URLs.</p>
        </header>
        <main>
          <div class="crumb"><a href="/">Home</a> › <a href="/sitemap.xml">Sitemap Index</a> › <strong>URL Sitemap</strong></div>
          <table>
            <thead>
              <tr><th class="url">URL</th><th class="small">Images</th><th class="small">Change Frequency</th><th class="small">Priority</th><th class="updated">Last Updated</th></tr>
            </thead>
            <tbody>
              <xsl:for-each select="s:urlset/s:url">
                <tr>
                  <td><a href="{s:loc}"><xsl:value-of select="s:loc"/></a></td>
                  <td><xsl:value-of select="count(image:image)"/></td>
                  <td><xsl:value-of select="s:changefreq"/></td>
                  <td>
                    <xsl:choose>
                      <xsl:when test="number(s:priority) &gt;= 0.8">High</xsl:when>
                      <xsl:when test="number(s:priority) &gt;= 0.5">Medium</xsl:when>
                      <xsl:otherwise>Low</xsl:otherwise>
                    </xsl:choose>
                  </td>
                  <td><xsl:value-of select="translate(substring(s:lastmod, 1, 19), 'T', ' ')"/> UTC</td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
        </main>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
